export const ErrorCodes = {
  // Auth errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  VERIFICATION_CODE_SENT: "VERIFICATION_CODE_SENT",
  VERIFICATION_CODE_SEND_ERROR: "VERIFICATION_CODE_SEND_ERROR",
  VERIFICATION_CODE_NOT_SENT: "VERIFICATION_CODE_NOT_SENT",
  INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
  VERIFICATION_CODE_EXPIRED: "VERIFICATION_CODE_EXPIRED",
  EMAIL_VERIFIED_SUCCESS: "EMAIL_VERIFIED_SUCCESS",
  EMAIL_VERIFICATION_ERROR: "EMAIL_VERIFICATION_ERROR",
  PHONE_VERIFIED_SUCCESS: "PHONE_VERIFIED_SUCCESS",
  PHONE_VERIFICATION_ERROR: "PHONE_VERIFICATION_ERROR",
  TOKEN_NOT_PROVIDED: "TOKEN_NOT_PROVIDED",
  INVALID_OR_EXPIRED_TOKEN: "INVALID_OR_EXPIRED_TOKEN",
  AUTHORIZATION_REQUIRED: "AUTHORIZATION_REQUIRED",
  ADMIN_RIGHTS_REQUIRED: "ADMIN_RIGHTS_REQUIRED",
  TOO_MANY_REQUESTS_IP: "TOO_MANY_REQUESTS_IP",
  TOO_MANY_LOGIN_ATTEMPTS: "TOO_MANY_LOGIN_ATTEMPTS",

  // User errors
  USER_REGISTERED: "USER_REGISTERED",
  REGISTRATION_SERVER_ERROR: "REGISTRATION_SERVER_ERROR",
  LOGIN_PASSWORD_REQUIRED: "LOGIN_PASSWORD_REQUIRED",
  INVALID_LOGIN_PASSWORD: "INVALID_LOGIN_PASSWORD",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_SERVER_ERROR: "LOGIN_SERVER_ERROR",
  USER_DATA: "USER_DATA",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

  // Booking errors
  TRIP_ID_SEATS_REQUIRED: "TRIP_ID_SEATS_REQUIRED",
  TRIP_NOT_FOUND: "TRIP_NOT_FOUND",
  NO_AVAILABLE_SEATS: "NO_AVAILABLE_SEATS",
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_PENDING: "BOOKING_PENDING",
  BOOKING_CREATE_ERROR: "BOOKING_CREATE_ERROR",
  BOOKINGS_FETCH_ERROR: "BOOKINGS_FETCH_ERROR",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_ACCESS_DENIED: "BOOKING_ACCESS_DENIED",
  BOOKING_FETCH_ERROR: "BOOKING_FETCH_ERROR",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_CANCEL_ERROR: "BOOKING_CANCEL_ERROR",
  ACTIVE_TRIPS_FETCH_ERROR: "ACTIVE_TRIPS_FETCH_ERROR",

  // Chat errors
  CHAT_NOT_FOUND: "CHAT_NOT_FOUND",
  CHAT_SERVER_ERROR: "CHAT_SERVER_ERROR",
  CHATID_TEXT_REQUIRED: "CHATID_TEXT_REQUIRED",
  CHAT_ACCESS_DENIED: "CHAT_ACCESS_DENIED",
  CHAT_SEND_ERROR: "CHAT_SEND_ERROR",
  SECOND_USER_MISSING: "SECOND_USER_MISSING",
  CHAT_ALREADY_EXISTS: "CHAT_ALREADY_EXISTS",
  CHAT_CREATE_ERROR: "CHAT_CREATE_ERROR",

  // Driver booking errors
  BOOKING_ALREADY_PROCESSED: "BOOKING_ALREADY_PROCESSED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CONFIRM_ERROR: "BOOKING_CONFIRM_ERROR",
  BOOKING_REJECTED: "BOOKING_REJECTED",
  BOOKING_REJECT_ERROR: "BOOKING_REJECT_ERROR",
  TRIP_HISTORY_FETCH_ERROR: "TRIP_HISTORY_FETCH_ERROR",
  BOOKING_CONFIRMED_SUCCESS: "BOOKING_CONFIRMED_SUCCESS",
  BOOKING_REJECTED_SUCCESS: "BOOKING_REJECTED_SUCCESS",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",

  // Map errors
  DRIVER_NOT_FOUND: "DRIVER_NOT_FOUND",
  FROM_TO_REQUIRED: "FROM_TO_REQUIRED",
  ROUTE_CALC_FAILED: "ROUTE_CALC_FAILED",
  ROUTE_CALC_ERROR: "ROUTE_CALC_ERROR",

  // Notification errors
  NOTIFICATIONS_FETCH_ERROR: "NOTIFICATIONS_FETCH_ERROR",
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  NOTIFICATION_MARKED_READ: "NOTIFICATION_MARKED_READ",
  NOTIFICATION_UPDATE_ERROR: "NOTIFICATION_UPDATE_ERROR",
  NOTIFICATIONS_MARKED_READ: "NOTIFICATIONS_MARKED_READ",
  NOTIFICATIONS_UPDATE_ERROR: "NOTIFICATIONS_UPDATE_ERROR",
  NOTIFICATION_DELETED: "NOTIFICATION_DELETED",
  NOTIFICATION_DELETE_ERROR: "NOTIFICATION_DELETE_ERROR",

  // Review errors
  REVIEW_FIELDS_REQUIRED: "REVIEW_FIELDS_REQUIRED",
  REVIEW_RATING_INVALID: "REVIEW_RATING_INVALID",
  REVIEW_NOT_ALLOWED: "REVIEW_NOT_ALLOWED",
  REVIEW_ADDED_SUCCESS: "REVIEW_ADDED_SUCCESS",
  REVIEW_CREATE_ERROR: "REVIEW_CREATE_ERROR",
  REVIEWS_FETCH_ERROR: "REVIEWS_FETCH_ERROR",

  // Trip errors
  TRIPS_SEARCH_ERROR: "TRIPS_SEARCH_ERROR",
  TRIP_DATETIME_FUTURE_REQUIRED: "TRIP_DATETIME_FUTURE_REQUIRED",
  TRIP_CREATED_SUCCESS: "TRIP_CREATED_SUCCESS",
  TRIP_CREATE_ERROR: "TRIP_CREATE_ERROR",
  TRIP_EDIT_NOT_FOUND_OR_NO_ACCESS: "TRIP_EDIT_NOT_FOUND_OR_NO_ACCESS",
  TRIP_UPDATED_SUCCESS: "TRIP_UPDATED_SUCCESS",
  TRIP_UPDATE_ERROR: "TRIP_UPDATE_ERROR",
  TRIP_DELETE_NOT_FOUND_OR_NO_ACCESS: "TRIP_DELETE_NOT_FOUND_OR_NO_ACCESS",
  TRIP_CANCELLED: "TRIP_CANCELLED",
  TRIP_DELETE_ERROR: "TRIP_DELETE_ERROR",
  TRIP_NOT_FOUND_OR_NO_ACCESS: "TRIP_NOT_FOUND_OR_NO_ACCESS",
  TRIP_ALREADY_FINISHED: "TRIP_ALREADY_FINISHED",
  CANNOT_FINISH_CANCELLED_TRIP: "CANNOT_FINISH_CANCELLED_TRIP",
  TRIP_FINISHED_SUCCESS: "TRIP_FINISHED_SUCCESS",
  TRIP_FINISH_ERROR: "TRIP_FINISH_ERROR",

  // File upload errors
  FILE_NOT_UPLOADED: "FILE_NOT_UPLOADED",
  AVATAR_UPLOADED_SUCCESS: "AVATAR_UPLOADED_SUCCESS",
  AVATAR_UPLOAD_ERROR: "AVATAR_UPLOAD_ERROR",
  FILES_NOT_UPLOADED: "FILES_NOT_UPLOADED",
  CAR_PHOTOS_UPLOADED_SUCCESS: "CAR_PHOTOS_UPLOADED_SUCCESS",
  CAR_PHOTOS_UPLOAD_ERROR: "CAR_PHOTOS_UPLOAD_ERROR",
  FILE_URL_REQUIRED: "FILE_URL_REQUIRED",
  INVALID_FILE_URL: "INVALID_FILE_URL",
  FILE_DELETED_SUCCESS: "FILE_DELETED_SUCCESS",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_DELETE_ERROR: "FILE_DELETE_ERROR",

  // User controller errors
  USERS_FETCH_ERROR: "USERS_FETCH_ERROR",
  EMPTY_OR_UNPARSED_REQUEST_BODY: "EMPTY_OR_UNPARSED_REQUEST_BODY",
  DRIVERS_ONLY_CAN_ADD_CAR: "DRIVERS_ONLY_CAN_ADD_CAR",
  CAR_DATA_UPDATED: "CAR_DATA_UPDATED",
  CAR_UPDATE_ERROR: "CAR_UPDATE_ERROR",
  USER_FETCH_ERROR: "USER_FETCH_ERROR",
  DRIVERS_FETCH_ERROR: "DRIVERS_FETCH_ERROR",
  EDIT_ONLY_OWN_PROFILE: "EDIT_ONLY_OWN_PROFILE",
  PROFILE_UPDATED_SUCCESS: "PROFILE_UPDATED_SUCCESS",
  USER_UPDATE_ERROR: "USER_UPDATE_ERROR",
  PROFILE_UPDATE_ERROR: "PROFILE_UPDATE_ERROR",

  // Admin errors
  USER_BLOCKED_FOREVER: "USER_BLOCKED_FOREVER",
  USER_UNBLOCKED: "USER_UNBLOCKED",
  CANNOT_DELETE_ADMIN: "CANNOT_DELETE_ADMIN",
  USER_DELETED_WITH_DATA: "USER_DELETED_WITH_DATA",
  COMPLAINT_USERID_REASON_REQUIRED: "COMPLAINT_USERID_REASON_REQUIRED",
  CANNOT_COMPLAIN_SELF: "CANNOT_COMPLAIN_SELF",
  COMPLAINT_SENT: "COMPLAINT_SENT",
  COMPLAINT_NOT_FOUND: "COMPLAINT_NOT_FOUND",

  //Notif
  NOTIFICATION_BOOKING_REQUEST_TO_DRIVER:
    "NOTIFICATION_BOOKING_REQUEST_TO_DRIVER",
  NOTIFICATION_BOOKING_REQUEST_TO_PASSENGER:
    "NOTIFICATION_BOOKING_REQUEST_TO_PASSENGER",
  NOTIFICATION_BOOKING_CONFIRMED_TO_DRIVER:
    "NOTIFICATION_BOOKING_CONFIRMED_TO_DRIVER",
  NOTIFICATION_BOOKING_CONFIRMED_AUTO_TO_DRIVER:
    "NOTIFICATION_BOOKING_CONFIRMED_AUTO_TO_DRIVER",
  NOTIFICATION_BOOKING_CONFIRMED_AUTO_TO_PASSENGER:
    "NOTIFICATION_BOOKING_CONFIRMED_AUTO_TO_PASSENGER",
  NOTIFICATION_BOOKING_CONFIRMED_TO_PASSENGER:
    "NOTIFICATION_BOOKING_CONFIRMED_TO_PASSENGER",
  NOTIFICATION_BOOKING_REJECTED_TO_PASSENGER:
    "NOTIFICATION_BOOKING_REJECTED_TO_PASSENGER",
  NOTIFICATION_BOOKING_CANCELLED_BY_PASSENGER_TO_DRIVER:
    "NOTIFICATION_BOOKING_CANCELLED_BY_PASSENGER_TO_DRIVER",
  NOTIFICATION_BOOKING_CANCELLED_BY_PASSENGER_TO_PASSENGER:
    "NOTIFICATION_BOOKING_CANCELLED_BY_PASSENGER_TO_PASSENGER",

  // Trip notifications
  NOTIFICATION_TRIP_COMPLETED_TO_DRIVER:
    "NOTIFICATION_TRIP_COMPLETED_TO_DRIVER",
  NOTIFICATION_TRIP_COMPLETED_TO_PASSENGER:
    "NOTIFICATION_TRIP_COMPLETED_TO_PASSENGER",
  NOTIFICATION_TRIP_STATUS_CHANGED_TO_PAID:
    "NOTIFICATION_TRIP_STATUS_CHANGED_TO_PAID",

  // Payment notifications
  NOTIFICATION_PAYMENT_SUCCESS: "NOTIFICATION_PAYMENT_SUCCESS",
  NOTIFICATION_PAYMENT_FAILED: "NOTIFICATION_PAYMENT_FAILED",

  // Info notifications
  NOTIFICATION_INFO_GENERAL: "NOTIFICATION_INFO_GENERAL",
  NOTIFICATION_SUCCESS_GENERAL: "NOTIFICATION_SUCCESS_GENERAL",
  NOTIFICATION_ERROR_GENERAL: "NOTIFICATION_ERROR_GENERAL",
};

// Тип для динамических ошибок с meta
export interface ErrorWithMeta {
  code: string;
  meta?: Record<string, any>;
}

// Тип для стандартного ответа с ошибкой
export interface ErrorResponse {
  success: false;
  code: string;
  meta?: Record<string, any>;
}

// Тип для стандартного успешного ответа
export interface SuccessResponse<T = any> {
  success: true;
  code?: string;
  data: T;
  meta?: Record<string, any>;
}
